name: Get Latest Tag

on:
  push:
    branches:
      - master

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest tag
        id: get-tag
        run: |
          # 获取最新的标签
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::set-output name=tag::$latest_tag"

      - name: Print latest tag
        run: echo "The latest tag is ${{ steps.get-tag.outputs.tag }}"
