name: 'Update UpGo version'
on:
  push:
    branches:
      - master

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      # 切换到github目录下面
      - name: "Checkout代码"
        uses: actions/checkout@v3
      - name: 更新 config.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: './conf/config.yaml'
          propertyPath: 'app.version'
          value: v2.0.0
          commitChange: false
      - name: 'path1'
        run: |
          echo "当前文件夹："
          pwd
          echo "当前文件夹列表："
          ls
          cd conf
          echo "curent dir is"
          pwd
