name: 更新UpGo版本
on:
  push:
    branches:
      - master

jobs:
  test-update-file:
    runs-on: ubuntu-latest
    steps:
      # 切换到github目录下面
      - name: "Checkout代码"
        uses: actions/checkout@v3
      - name: '打印当前目录'
        run: |
          echo "当前文件夹："
          pwd
          echo "当前文件夹列表："
          ls
          cd conf
          echo "curent dir is"
          pwd
      - name: 更新 config.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          branch: master
          targetBranch: master
          description: Test GitHub Action
          message: 'Update Upgo Version' 
          title: 'Version Updates '
          token: ${{ secrets.ACCESS_TOKEN }}
          valueFile: 'conf/config.yml'
          propertyPath: 'app.version'
          value: v2.0.0
          commitChange: true
      - name: 'path1'
        run: |
          echo "当前文件夹："
          pwd
          echo "当前文件夹列表："
          ls
          cd conf
          echo "curent dir is"
          pwd
